feat: add a list of elements supporting disabled attribute
eps1lon/dom-accessibility-api pull request #919
Opened 2023-03-25 06:43 UTC by MatanBobi

This was discussed in https://github.com/testing-library/dom-testing-library/pull/1221#discussion_r1147913695

I wasn't sure where's the right place to put this one, please let me know if there's a better place for this and I'll change (I thought about creating a new file but didn't want to make a mess).

Thanks!

2023-03-25 07:49 UTC, eps1lon requested changes
These seems very much like an implementation detail. I assumed you meant to add a method that checks if an element is considered disabled in the a11y tree.

But this is too low level to be considered for a public API.

2023-03-25 16:00 UTC, MatanBobi commented
> These seems very much like an implementation detail. I assumed you meant to add a method that checks if an element is considered disabled in the a11y tree.
> 
> But this is too low level to be considered for a public API.

That makes a lot more sense.
Will fix this, thanks.

2023-05-07 19:54 UTC, eps1lon commented on sources/__tests__/is-disabled.js
> +describe("isInaccessible", () => {
```suggestion
describe("isDisabled", () => {
```

2023-05-07 19:57 UTC, eps1lon approved these changes
Thanks!

2023-05-07 20:02 UTC, merged